In [ ]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt

os.chdir('/Users/DAY\Desktop\DIPLOMADO ANÁLISIS DE DATOS')

In [3]:
#Lectura del archivo, head, tail, sample, describe.  Validación de columnas numéricas para que funcione con todas.  
df=pd.read_csv('vgsales.csv')

In [4]:
df.head(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [5]:
df.tail(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

In [6]:
df.sample(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
15246,15249,Sakura Wars 1 & 2,PSP,2006.0,Strategy,Sega,0.00,0.00,0.02,0.00,0.02
12642,12644,Racing Gears Advance,GBA,2004.0,Racing,Zoo Digital Publishing,0.04,0.02,0.00,0.00,0.06
4150,4152,Bravely Second: End Layer,3DS,2015.0,Role-Playing,Nintendo,0.16,0.11,0.18,0.03,0.47
9591,9593,LEGO Batman 2: DC Super Heroes,WiiU,2013.0,Action,Warner Bros. Interactive Entertainment,0.05,0.07,0.00,0.01,0.13
12325,12327,Crimson Gem Saga,PSP,2008.0,Role-Playing,Sega,0.06,0.00,0.00,0.00,0.06

In [7]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [9]:
num_cols = df.select_dtypes(include="number").columns
print(num_cols)

Index(['Rank', 'Year', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales',
       'Global_Sales'],
      dtype='object')

In [10]:
df[num_cols].corr()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Rank,1.000000,0.178814,-0.401362,-0.379123,-0.267785,-0.332986,-0.427407
Year,0.178814,1.000000,-0.091402,0.006014,-0.169316,0.041058,-0.074735
NA_Sales,-0.401362,-0.091402,1.000000,0.767727,0.449787,0.634737,0.941047
EU_Sales,-0.379123,0.006014,0.767727,1.000000,0.435584,0.726385,0.902836
JP_Sales,-0.267785,-0.169316,0.449787,0.435584,1.000000,0.290186,0.611816
Other_Sales,-0.332986,0.041058,0.634737,0.726385,0.290186,1.000000,0.748331
Global_Sales,-0.427407,-0.074735,0.941047,0.902836,0.611816,0.748331,1.000000

### Totales

In [11]:
total_videojuegos = df.shape[0]
print("Total de videojuegos analizados:", total_videojuegos)

Total de videojuegos analizados: 16598

In [12]:
total_generos = df["Genre"].nunique()
print("Total de géneros analizados:", total_generos)

Total de géneros analizados: 12

In [13]:
total_plataformas = df["Platform"].nunique()
print("Total de plataformas analizadas:", total_plataformas)

Total de plataformas analizadas: 31

### Ventas

In [14]:
#Total de ventas por año
ventas_por_anio =(df.groupby("Year")[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"]].sum().reset_index())
ventas_por_anio

      Year  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0   1980.0     10.59      0.67      0.00         0.12         11.38
1   1981.0     33.40      1.96      0.00         0.32         35.77
2   1982.0     26.92      1.65      0.00         0.31         28.86
3   1983.0      7.76      0.80      8.10         0.14         16.79
4   1984.0     33.28      2.10     14.27         0.70         50.36
5   1985.0     33.73      4.74     14.56         0.92         53.94
6   1986.0     12.50      2.84     19.81         1.93         37.07
7   1987.0      8.46      1.41     11.63         0.20         21.74
8   1988.0     23.87      6.59     15.76         0.99         47.22
9   1989.0     45.15      8.44     18.36         1.50         73.45
10  1990.0     25.46      7.63     14.88         1.40         49.39
11  1991.0     12.76      3.95     14.78         0.74         32.23
12  1992.0     33.87     11.71     28.91         1.65         76.16
13  1993.0     15.12      4.65     25.33         0.89         45.98
14  1994.0     28.15     14.88     33.99         2.20         79.17
15  1995.0     24.82     14.90     45.75         2.64         88.11
16  1996.0     86.76     47.26     57.44         7.69        199.15
17  1997.0     94.75     48.32     48.87         9.13        200.98
18  1998.0    128.36     66.90     50.04        11.03        256.47
19  1999.0    126.06     62.67     52.34        10.05        251.27
20  2000.0     94.49     52.75     42.77        11.62        201.56
21  2001.0    173.98     94.89     39.86        22.76        331.47
22  2002.0    216.19    109.74     41.76        27.28        395.52
23  2003.0    193.59    103.81     34.20        26.01        357.85
24  2004.0    222.59    107.32     41.65        47.29        419.31
25  2005.0    242.61    121.94     54.28        40.58        459.94
26  2006.0    263.12    129.24     73.73        54.43        521.04
27  2007.0    312.05    160.50     60.29        77.60        611.13
28  2008.0    351.44    184.40     60.26        82.39        678.90
29  2009.0    338.85    191.59     61.89        74.77        667.30
30  2010.0    304.24    176.73     59.49        59.90        600.45
31  2011.0    241.06    167.44     53.04        54.39        515.99
32  2012.0    154.96    118.78     51.74        37.82        363.54
33  2013.0    154.77    125.80     47.59        39.82        368.11
34  2014.0    131.97    125.65     39.46        40.02        337.05
35  2015.0    102.82     97.71     33.72        30.01        264.44
36  2016.0     22.66     26.76     13.70         7.75         70.93
37  2017.0      0.00      0.00      0.05         0.00          0.05
38  2020.0      0.27      0.00      0.00         0.02          0.29

In [16]:
#Juegos más vendidos por año
idx = df.groupby("Year")["Global_Sales"].idxmax()
juegos_top_por_anio = df.loc[idx, ["Year", "Name", "Global_Sales"]].reset_index(drop=True)
juegos_top_por_anio

      Year                                              Name  Global_Sales
0   1980.0                                         Asteroids          4.31
1   1981.0                                          Pitfall!          4.50
2   1982.0                                           Pac-Man          7.81
3   1983.0                                          Baseball          3.20
4   1984.0                                         Duck Hunt         28.31
5   1985.0                                 Super Mario Bros.         40.24
6   1986.0                               The Legend of Zelda          6.51
7   1987.0                   Zelda II: The Adventure of Link          4.38
8   1988.0                               Super Mario Bros. 3         17.28
9   1989.0                                            Tetris         30.26
10  1990.0                                 Super Mario World         20.61
11  1991.0           The Legend of Zelda: A Link to the Past          4.61
12  1992.0                Super Mario Land 2: 6 Golden Coins         11.18
13  1993.0                             Super Mario All-Stars         10.55
14  1994.0                               Donkey Kong Country          9.30
15  1995.0         Donkey Kong Country 2: Diddy's Kong Quest          5.15
16  1996.0                          Pokemon Red/Pokemon Blue         31.37
17  1997.0                                      Gran Turismo         10.95
18  1998.0           Pokémon Yellow: Special Pikachu Edition         14.64
19  1999.0                       Pokemon Gold/Pokemon Silver         23.10
20  2000.0                           Pokémon Crystal Version          6.39
21  2001.0                            Gran Turismo 3: A-Spec         14.98
22  2002.0                       Grand Theft Auto: Vice City         16.15
23  2003.0                        Need for Speed Underground          7.20
24  2004.0                     Grand Theft Auto: San Andreas         20.81
25  2005.0                                        Nintendogs         24.76
26  2006.0                                        Wii Sports         82.74
27  2007.0                                           Wii Fit         22.72
28  2008.0                                    Mario Kart Wii         35.82
29  2009.0                                 Wii Sports Resort         33.00
30  2010.0                                Kinect Adventures!         21.82
31  2011.0                    Call of Duty: Modern Warfare 3         14.76
32  2012.0                        Call of Duty: Black Ops II         14.03
33  2013.0                                Grand Theft Auto V         21.40
34  2014.0                                Grand Theft Auto V         11.98
35  2015.0                         Call of Duty: Black Ops 3         14.24
36  2016.0                                           FIFA 17          4.77
37  2017.0  Phantasy Star Online 2 Episode 4: Deluxe Package          0.03
38  2020.0                            Imagine: Makeup Artist          0.29

In [17]:
#Plataformas con mas ingresos por año
ventas_plataforma_anio = (df.groupby(["Year", "Platform"])[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"]].sum().reset_index())
ventas_plataforma_anio

       Year Platform  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0    1980.0     2600     10.59      0.67      0.00         0.12         11.38
1    1981.0     2600     33.40      1.96      0.00         0.32         35.77
2    1982.0     2600     26.92      1.65      0.00         0.31         28.86
3    1983.0     2600      5.44      0.34      0.00         0.06          5.83
4    1983.0      NES      2.32      0.46      8.10         0.08         10.96
..      ...      ...       ...       ...       ...          ...           ...
236  2016.0     X360      0.36      0.40      0.00         0.07          0.83
237  2016.0     XOne      6.69      4.63      0.01         1.05         12.37
238  2017.0      PS4      0.00      0.00      0.03         0.00          0.03
239  2017.0      PSV      0.00      0.00      0.02         0.00          0.02
240  2020.0       DS      0.27      0.00      0.00         0.02          0.29

[241 rows x 7 columns]

In [18]:
#Gráfico de comparación de ventas entre géneros por año
ventas_genero_anio =(df.groupby(["Year", "Genre"])["Global_Sales"].sum().reset_index())

import plotly.express as px
fig = px.line(ventas_genero_anio,x="Year",y="Global_Sales",color="Genre",title="Comparación de ventas por género a lo largo del tiempo")
fig.show()

In [19]:
#Insights: 2 gráficos adicionales interesantes
#Insight 1: Ventas por región (comparación)
ventas_region = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].sum().reset_index()
ventas_region.columns = ["Region", "Ventas"]

fig = px.bar(ventas_region, x="Region",y="Ventas",color="Region", title="Ventas totales por región",color_discrete_sequence=px.colors.qualitative.Set2)
fig.show()

In [20]:
#Insight 2: Top 10 plataformas con mayores ventas globales
top_plataformas = (df.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False).head(10).reset_index())

fig = px.bar(top_plataformas,x="Platform", y="Global_Sales",color="Platform",title="Top 10 plataformas con mayores ventas globales",
             color_discrete_sequence=px.colors.qualitative.Pastel)
fig.show()

In [21]:
#Para saber el año más reciente en el Dataset
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

last_year = int(df["Year"].max())

years_4 = list(range(last_year - 3, last_year + 1))

df_4 = df[df["Year"].isin(years_4)].copy()

print("Últimos 4 años:", years_4)
print("Filas en ventana:", df_4.shape[0])

Últimos 4 años: [2017, 2018, 2019, 2020]
Filas en ventana: 4

In [22]:
# Limpieza básica de nombres de columnas
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

In [23]:
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
print("Años (min, max):", df["Year"].min(), df["Year"].max())
print("Años NaN:", df["Year"].isna().sum())

Años (min, max): 1980.0 2020.0
Años NaN: 271

In [24]:
last_year = int(df["Year"].dropna().max())
years_4 = list(range(last_year - 3, last_year + 1))
print("Últimos 4 años:", years_4)

df_4 = df[df["Year"].isin(years_4)].copy()
print("Filas en df_4:", df_4.shape)
print("Años presentes en df_4:", sorted(df_4["Year"].dropna().unique()))

Últimos 4 años: [2017, 2018, 2019, 2020]
Filas en df_4: (4, 11)
Años presentes en df_4: [np.float64(2017.0), np.float64(2020.0)]

In [25]:
print("Nulos en Genre (df_4):", df_4["Genre"].isna().sum())
print(df_4[["Year", "Name", "Genre"]].head(10))

Nulos en Genre (df_4): 0
         Year                                              Name         Genre
5957   2020.0                            Imagine: Makeup Artist    Simulation
14390  2017.0  Phantasy Star Online 2 Episode 4: Deluxe Package  Role-Playing
16241  2017.0  Phantasy Star Online 2 Episode 4: Deluxe Package  Role-Playing
16438  2017.0                  Brothers Conflict: Precious Baby        Action

In [26]:
print(df.columns.tolist())
print("df_4 shape:", df_4.shape)
print("Genre nulos df_4:", df_4["Genre"].isna().sum() if "Genre" in df_4.columns else "No existe Genre")

['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']
df_4 shape: (4, 11)
Genre nulos df_4: 0

In [27]:
df.groupby("Year").size().tail(10)

Year
2009.0    1431
2010.0    1259
2011.0    1139
2012.0     657
2013.0     546
2014.0     582
2015.0     614
2016.0     344
2017.0       3
2020.0       1
dtype: int64

In [28]:
df_4 = df[df["Year"].between(2013, 2016)].copy()
df_4.shape

(2086, 11)

### Crecimiento por GÉNERO

In [29]:
#Aunque el dataset contiene registros hasta el año 2020, los años más recientes 
# presentan un número muy reducido de observaciones (por ejemplo, solo 3 juegos en 2017 y 1 en 2020).
#Para garantizar un análisis de crecimiento representativo, se seleccionaron los últimos cuatro años con volumen significativo de datos (2013–2016), 
#permitiendo obtener conclusiones válidas sobre tendencias de mercado.

genre_year = (df_4.groupby(["Year", "Genre"])["Global_Sales"].sum().reset_index())

In [30]:
genre_pivot = genre_year.pivot(index="Genre",columns="Year",values="Global_Sales").fillna(0)

In [31]:
genre_pivot["Crecimiento"] = genre_pivot[2016] - genre_pivot[2013]
genre_growth = genre_pivot.sort_values("Crecimiento", ascending=False)

print("Mayor crecimiento género:")
print(genre_growth.head(1))

print("\nMenor crecimiento género:")
print(genre_growth.tail(1))

Mayor crecimiento género:
Year    2013.0  2014.0  2015.0  2016.0  Crecimiento
Genre
Puzzle    0.99     1.5     0.7     0.0        -0.99

Menor crecimiento género:
Year    2013.0  2014.0  2015.0  2016.0  Crecimiento
Genre
Action  125.22   99.02    70.7   19.91      -105.31

### Crecimiento por PLATAFORMA

In [32]:
platform_year = (df_4.groupby(["Year", "Platform"])["Global_Sales"].sum().reset_index())

platform_pivot = platform_year.pivot(index="Platform",columns="Year",values="Global_Sales").fillna(0)

platform_pivot["Crecimiento"] = platform_pivot[2016] - platform_pivot[2013]

platform_growth = platform_pivot.sort_values("Crecimiento", ascending=False)

print("Mayor crecimiento plataforma:")
print(platform_growth.head(1))

print("\nMenor crecimiento plataforma:")
print(platform_growth.tail(1))

Mayor crecimiento plataforma:
Year      2013.0  2014.0  2015.0  2016.0  Crecimiento
Platform
PS4        24.76   98.76   115.3   39.25        14.49

Menor crecimiento plataforma:
Year      2013.0  2014.0  2015.0  2016.0  Crecimiento
Platform
PS3       117.39   50.96   18.22    2.59       -114.8

### Videojuego con mayor y menor crecimiento

In [33]:
top_games = df_4.loc[df_4.groupby("Year")["Global_Sales"].idxmax(),["Year", "Name", "Platform", "Genre", "Global_Sales"]].sort_values("Year")

top_2013 = top_games[top_games["Year"] == 2013]
top_2016 = top_games[top_games["Year"] == 2016]

top_2013, top_2016

(      Year                Name Platform   Genre  Global_Sales
 16  2013.0  Grand Theft Auto V      PS3  Action          21.4,
        Year     Name Platform   Genre  Global_Sales
 221  2016.0  FIFA 17      PS4  Sports          4.77)

- Dado que el dataset contiene un único año de registro por videojuego, el crecimiento a nivel de título se interpretó como el cambio en el videojuego líder del mercado entre el primer y último año del periodo analizado.

### INSIGHTS ADICIONALES

In [34]:
#INSIGHT 1 — Géneros con mayor crecimiento en una región
#El mercado no crece igual en todas las regiones.
genre_region = (df_4.groupby(["Year", "Genre"])["NA_Sales"].sum().reset_index())

genre_pivot_na = genre_region.pivot(index="Genre",columns="Year",values="NA_Sales").fillna(0)

genre_pivot_na["Crecimiento_NA"] = genre_pivot_na[2016] - genre_pivot_na[2013]

genre_pivot_na.sort_values("Crecimiento_NA", ascending=False).head(5)

Year        2013.0  2014.0  2015.0  2016.0  Crecimiento_NA
Genre
Puzzle        0.19    0.62    0.05    0.00           -0.19
Adventure     1.63    1.94    2.76    0.34           -1.29
Fighting      3.18    6.89    3.60    1.60           -1.58
Simulation    2.26    1.22    1.13    0.00           -2.26
Strategy      2.39    0.16    0.57    0.11           -2.28

In [35]:
#INSIGHT 2 — Plataformas con mayor venta promedio por juego
#No solo importa vender mucho, importa cuánto vende cada juego en promedio
df_2016 = df_4[df_4["Year"] == 2016]

platform_avg = (df_2016.groupby("Platform").agg(Juegos=("Name", "count"), Ventas=("Global_Sales", "sum")))

platform_avg["Venta_Promedio"] = (platform_avg["Ventas"] / platform_avg["Juegos"])*100

platform_avg.sort_values("Venta_Promedio", ascending=False).head(5)

          Juegos  Ventas  Venta_Promedio
Platform
PS4          107   39.25       36.682243
WiiU          10    3.29       32.900000
XOne          54   12.37       22.907407
3DS           35    6.60       18.857143
X360           8    0.83       10.375000

### Gráficos presentación

In [37]:
import pandas as pd
import numpy as np
import plotly.express as px

df = pd.read_csv("vgsales.csv")
df.columns = df.columns.str.strip()

df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

y0, y1 = 2013, 2016
df_4 = df[df["Year"].between(y0, y1)].copy()

sales_cols = ["NA_Sales","EU_Sales","JP_Sales","Other_Sales","Global_Sales"]
sales_cols

['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

In [40]:
# SLIDE 2: Ventas totales por año (Global)

ventas_por_anio = (df_4.groupby("Year")[sales_cols].sum().reset_index().sort_values("Year"))

fig2 = px.bar( ventas_por_anio,x="Year", y="Global_Sales",title=f"Ventas globales totales por año ({y0}–{y1})",
              text_auto=".2f", width=1000,height=500, color="Year",color_discrete_sequence=px.colors.qualitative.Pastel)
fig2.show()

In [43]:
# SLIDE 3: Ventas por género por año (líneas)
genre_year = (df_4.groupby(["Year","Genre"])["Global_Sales"].sum().reset_index())

top_genres = (df_4.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False).head(6).index)

genre_year_top = genre_year[genre_year["Genre"].isin(top_genres)].sort_values(["Year","Genre"])

fig3 = px.line(genre_year_top,x="Year",y="Global_Sales",color="Genre",markers=True,
               title=f"Evolución de ventas globales por género (Top 6) ({y0}–{y1})",width=1000,height=500)
fig3.show()

In [44]:
# SLIDE 4: Crecimiento por plataforma (2016 - 2013)
platform_year = (df_4.groupby(["Year","Platform"])["Global_Sales"].sum() .reset_index())

platform_pivot = (platform_year.pivot(index="Platform", columns="Year", values="Global_Sales").fillna(0))

for y in [y0, y1]:
    if y not in platform_pivot.columns:
        platform_pivot[y] = 0

platform_pivot["Crecimiento"] = platform_pivot[y1] - platform_pivot[y0]

top_plat = platform_pivot["Crecimiento"].abs().sort_values(ascending=False).head(10).index
platform_growth_plot = platform_pivot.loc[top_plat, ["Crecimiento"]].reset_index().sort_values("Crecimiento", ascending=False)

fig4 = px.bar(platform_growth_plot,x="Platform",y="Crecimiento",color="Platform",
              title=f"Crecimiento de ventas globales por plataforma ({y1} – {y0}) | Top 10",text_auto=".2f",width=1000,height=500)

fig4.update_layout(showlegend=False)
fig4.show()

In [45]:
# SLIDE 5: Juegos líderes del mercado (Top juego 2013 vs Top juego 2016)
df_2013 = df_4[df_4["Year"] == y0]
df_2016 = df_4[df_4["Year"] == y1]

top_game_2013 = df_2013.loc[df_2013["Global_Sales"].idxmax(), ["Year","Name","Platform","Genre","Global_Sales"]]
top_game_2016 = df_2016.loc[df_2016["Global_Sales"].idxmax(), ["Year","Name","Platform","Genre","Global_Sales"]]

top_games_compare = pd.DataFrame([top_game_2013, top_game_2016])
top_games_compare["Label"] = top_games_compare["Year"].astype(int).astype(str) + " — " + top_games_compare["Name"]

fig5 = px.bar(top_games_compare,x="Label",y="Global_Sales",color="Year",title=f"Cambio en el videojuego más vendido (Global) {y0} vs {y1}",
    text_auto=".2f",width=1000,height=500)
fig5.update_xaxes(title="")
fig5.show()

In [46]:
# SLIDE 6 (Insight 1): Crecimiento de géneros por región (NA) (2016 - 2013)
genre_na_year = (df_4.groupby(["Year","Genre"])["NA_Sales"].sum().reset_index())

genre_na_pivot = (genre_na_year.pivot(index="Genre", columns="Year", values="NA_Sales").fillna(0))

for y in [y0, y1]:
    if y not in genre_na_pivot.columns:
        genre_na_pivot[y] = 0

genre_na_pivot["Crecimiento_NA"] = genre_na_pivot[y1] - genre_na_pivot[y0]

top_gen_na = genre_na_pivot["Crecimiento_NA"].abs().sort_values(ascending=False).head(8).index
genre_na_plot = genre_na_pivot.loc[top_gen_na, ["Crecimiento_NA"]].reset_index().sort_values("Crecimiento_NA", ascending=False)

fig6a = px.bar(genre_na_plot,x="Genre",y="Crecimiento_NA",color="Genre",title=f"Crecimiento de ventas en NA por género ({y1} – {y0}) | Top 8",
    text_auto=".2f",width=1000,height=500)
fig6a.update_layout(showlegend=False)
fig6a.show()

In [48]:
# SLIDE 6 (Insight 2): Eficiencia (venta promedio por título) por plataforma en 2016
df_last = df[df["Year"] == y1].copy()

plat_eff = (df_last.groupby("Platform").agg(Juegos=("Name","count"), Ventas_Global=("Global_Sales","sum")).reset_index())

plat_eff["Venta_Promedio"] = plat_eff["Ventas_Global"] / plat_eff["Juegos"]

plat_eff_filtered = (plat_eff[plat_eff["Juegos"] >= 10].sort_values("Venta_Promedio", ascending=False).head(10))

fig6b = px.bar(plat_eff_filtered,x="Platform",y="Venta_Promedio",color="Platform",
    title=f"Venta promedio por videojuego (Global) por plataforma en {y1} | Top 10 (>=10 juegos)",text_auto=".2f",
    width=1000,height=500)
fig6b.update_layout(showlegend=False)
fig6b.show()